Include example data input in repository
scitools-classroom/iris-mesh-tutorial pull request #27
Opened 2023-03-02 14:09 UTC by BHFock

Include a 7.1 mb example data folder in the repository to allow running the examples from section 1 to 5

2023-03-13 11:27 UTC, pp-mo requested changes

2023-03-13 11:27 UTC, pp-mo commented on notebooks/testdata_fetching.py
> +    #if use_newer_smaller_c48_data:
I think the time has now come to remove the `switch_data` routine entirely.
The only remaining reference to it that I can find is [here](https://github.com/scitools-classroom/iris-mesh-tutorial/blob/main/notebooks/.notebook_shadow_copies/Bonus_03_MeshCube_Extraction.md?plain=1#L39)
  -- which I think does nothing, since the default is now 'small data' anyway.

So, can you  just assign directly to the global path variables, and remove this routine + the remaining references (the one above, and below in this file) ?

2023-03-13 12:05 UTC, BHFock commented on notebooks/testdata_fetching.py
> +    #if use_newer_smaller_c48_data:
I addressed that point in a6a1a0cdb7295d681e259aa4a464b488d14bb7af

2023-03-14 13:27 UTC, pp-mo commented on notebooks/testdata_fetching.py
> +    #if use_newer_smaller_c48_data:
Looks fine, but you still need to remove [this reference to it](https://github.com/scitools-classroom/iris-mesh-tutorial/blob/main/notebooks/.notebook_shadow_copies/Bonus_03_MeshCube_Extraction.md?plain=1#L39) as well.

2023-03-17 10:47 UTC, BHFock commented on notebooks/testdata_fetching.py
> +    #if use_newer_smaller_c48_data:
https://github.com/scitools-classroom/iris-mesh-tutorial/commit/ee82236d7572bceafdec48690b26992626b9f054 adds a missed detail for https://github.com/scitools-classroom/iris-mesh-tutorial/commit/02296f61997358d1039630ac7a3e59736c247dfc

2023-03-17 16:00 UTC, pp-mo approved these changes

2023-03-17 16:09 UTC, merged