Add regridding section
scitools-classroom/iris-mesh-tutorial pull request #9
Opened 2023-01-19 15:25 UTC by stephenworsley

2023-01-20 10:48 UTC, BHFock commented on notebooks/.notebook_shadow_copies/Sec_05_Regridding.md
> +The reason this is done in two steps is because initialising a regridder is potentially quite expensive if the grids or meshes involved are large. Once initialised, a regridder can regrid many source
In practice I expect the same grid mesh pairs to be used by many users. Is it possible to store a regridder to a file, and build up a library of pre-calculated regridders for frequently used grid mesh pairs?

2023-01-20 11:16 UTC, BHFock commented on notebooks/.notebook_shadow_copies/Sec_05_Regridding.md
> +The reason this is done in two steps is because initialising a regridder is potentially quite expensive if the grids or meshes involved are large. Once initialised, a regridder can regrid many source
I learned now that saving regridders is possible with https://iris-esmf-regrid.readthedocs.io/en/latest/_api_generated/esmf_regrid.experimental.io.html#esmf_regrid.experimental.io.save_regridder. Maybe we could add a half sentence with that link here?

2023-01-20 13:40 UTC, pp-mo requested changes
Some food for thought.
I may have more to add later, but I want to get these (and I want a link to reference in another issue!)

2023-01-20 13:40 UTC, pp-mo commented on notebooks/.notebook_shadow_copies/Sec_05_Regridding.md
> +```python
I don't fully understand this.  
It says "Since these arcs are 180 degrees it is necessary to have a resolution argument."  But this now applys only to the _longitudinal_ edges, so I guess it is saying we require a resolution>1 to resolve full-range cells in **_either_** lat or lon, which are unrepresentable in ESMF ??
But, that seems also to imply that resolution is dividing **_all_** (4) edges of target cells.
This is not clear, since the docstring suggests it is specific to latitude, as in 
> "represents the amount of latitude slices".

I guess this is not the place to explain it all, but we clearly need to be very careful not to say anything misleading or not-quite-true.  Which may well apply to my suggested texts above.

2023-01-23 09:35 UTC, stephenworsley commented on notebooks/.notebook_shadow_copies/Sec_05_Regridding.md
> +```python
So internally, I believe the logic is that vertical resolution is only used in the specific case where the bounds are [-90, 90] in which case it is effectively set to 2 and in all other cases horizontal resolution is the only one used. I suppose the exercise here kind of suggests otherwise, but I think this might be a bit too deep into the internals to get into here.

2023-01-25 00:46 UTC, pp-mo commented on notebooks/.notebook_shadow_copies/Sec_05_Regridding.md
> +regridder = MeshToGridESMFRegridder(mesh_cube, grid_cube)
We need to defer this to a general issue == are we going to re-style this notebook or not.
Now planning to discuss that in-person/offline.

2023-01-25 01:02 UTC, pp-mo commented on notebooks/.notebook_shadow_copies/Sec_05_Regridding.md
> +We can then plot the difference between the UM data and the data regridded from LFRic. Since our data is now on a latlon grid we can do this with matplotlib as normal.
I think it may be more important to say that "Since our data is now on a latlon grid" we can now **subtract to get the difference between this and the UM equivalent data**.

2023-01-25 02:06 UTC, pp-mo approved these changes
I have made further some comments + suggestions, but I think we could get on and merge this, and address those issues later.
Quick list -
  - [ ] [align sample code with prompt](https://github.com/scitools-classroom/iris-mesh-tutorial/pull/9#discussion_r1086115163)
  - [ ] [clearly state cost/accuracy tradeoff](https://github.com/scitools-classroom/iris-mesh-tutorial/pull/9#discussion_r1086116100)
  - [ ] small fixes to sample code [here](https://github.com/scitools-classroom/iris-mesh-tutorial/pull/9#discussion_r1086116603) 
  - [ ] ... and to same [here](https://github.com/scitools-classroom/iris-mesh-tutorial/pull/9#discussion_r1086118554)
  - [ ] review [lengthy calc](https://github.com/scitools-classroom/iris-mesh-tutorial/pull/9#discussion_r1086138303)
  - [ ] ?? convert all to C48 data
  - [ ] ??convert all to use (mostly) user-provided code in examples

2023-01-25 02:06 UTC, pp-mo commented on notebooks/.notebook_shadow_copies/Sec_05_Regridding.md
> +um_lon_band_mean_calculator = MeshToGridESMFRegridder(temp_slice, target_cube_lons, resolution=2)
For me, this step is currently taking an extremely long time ~1m40, , and about half the VDI memory (~2Gb).
So I think that needs reviewing for practicality.
NB with latest code we can "switch" to C48-sized data, which is over 10x smaller (221k -> 14k points).  
This may well be worth doing (we should probably make it standard).  
But it will affect the current results + so may require some adjustment to be made (e.g. might then be too fast to demonstrate efficiency changes !)

2023-01-25 02:11 UTC, merged

2023-01-25 02:16 UTC, pp-mo commented
Outstanding suggestions here : https://github.com/scitools-classroom/iris-mesh-tutorial/issues/11

2023-01-25 13:49 UTC, stephenworsley commented on notebooks/.notebook_shadow_copies/Sec_05_Regridding.md
> +um_lon_band_mean_calculator = MeshToGridESMFRegridder(temp_slice, target_cube_lons, resolution=2)
So it looks like this problem is specific to longitude bands and performance is a lot better with latitude bands. I think this might have something to do with ESMF not liking long, thin cells. I've raised an issue here https://github.com/SciTools-incubator/iris-esmf-regrid/issues/234 . Unfortunately, when taking the latitude band means there is a lot less visible detail in the resulting plot. I might try experimenting with other variables, but I think this is a reasonable trade off compared to minute long run times or C48 data.

2023-01-25 14:29 UTC, pp-mo commented on notebooks/.notebook_shadow_copies/Sec_05_Regridding.md
> +um_lon_band_mean_calculator = MeshToGridESMFRegridder(temp_slice, target_cube_lons, resolution=2)
Since merging this, I've also tested it with the newer C48 data.
Unfortunately, that is possibly _too_ small, since the operations get so quick as to make the measurements less certain.
This op took about 1.6 seconds, instead of ~100.